<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lajang</name>
   <tag></tag>
   <elementGuidId>52660ead-296b-4604-938f-c9fd48d2825f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#af59ed5a50d6-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='af59ed5a50d6-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0044431-54f5-4a05-9cf2-a2ab7ce7ca44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>8afc0bd6-2814-4a2e-90fc-51a5e5cd5f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>41e5c554-7ca9-4b75-af38-96e4a1832ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3083e078-2ab0-441e-80c9-6d1ba3c215da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>af59ed5a50d6-0</value>
      <webElementGuid>c48d9845-14b0-4fed-8bc9-570e5a27079e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lajang</value>
      <webElementGuid>be41cddb-bd0f-4d8c-bc00-72bc29ade081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;af59ed5a50d6-0&quot;)</value>
      <webElementGuid>a831e953-be70-4e7f-ad63-4bf5d9d7b2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af59ed5a50d6-0']</value>
      <webElementGuid>9ea7031b-be49-4542-af86-3be8d7f6dbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af59ed5a50d6']/div/div[2]/div</value>
      <webElementGuid>5e497559-6f24-4e2e-a0c5-a16402b0b35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Status'])[1]/following::div[5]</value>
      <webElementGuid>f4d08e37-48f6-40ed-b002-3d204ff3c515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[10]</value>
      <webElementGuid>370519c1-0541-4fde-bac2-248425ae8ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kawin'])[1]/preceding::div[1]</value>
      <webElementGuid>d93b2cea-4a84-4cf8-bcaf-577904db936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>3d861069-5027-4566-a5aa-836ee11e4266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af59ed5a50d6-0' and (text() = 'Lajang' or . = 'Lajang')]</value>
      <webElementGuid>6472ae3b-c8aa-4e91-a3f0-bed6b3f89af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
