<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lulus Kuliah</name>
   <tag></tag>
   <elementGuidId>de8e183b-3bf1-4d58-b16f-0d7c8641438b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a9ccc3db9791-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a9ccc3db9791-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98bd80af-346a-44de-b13a-871dcfa90342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>0a68f26e-e4cc-46fc-91d1-52d4bd1ec48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>498aa97e-96d0-41cd-a319-1faa87ca9020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>918245a0-fb8d-41fb-ad27-dd136028ab51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a9ccc3db9791-1</value>
      <webElementGuid>2f14272a-0fe2-405c-9eca-d409eadb885d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lulus Kuliah</value>
      <webElementGuid>08fa82fe-c370-4439-9769-13e148f2c57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a9ccc3db9791-1&quot;)</value>
      <webElementGuid>4fe55924-1d20-4223-ba22-3d602baca042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a9ccc3db9791-1']</value>
      <webElementGuid>d2915fb6-17b8-4346-a93e-9baef56ee55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a9ccc3db9791']/div/div[2]/div[2]</value>
      <webElementGuid>744fb9ed-1794-4023-be55-0dcb3b04fb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa Aktif'])[1]/following::div[1]</value>
      <webElementGuid>5dff23f2-1683-4baa-b007-af86e91358d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Pendidikan Terakhir'])[1]/following::div[6]</value>
      <webElementGuid>f58512f8-105d-4ea5-8e57-bea458fc36c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus SMA/SMK Sederajat'])[1]/preceding::div[1]</value>
      <webElementGuid>8b179c2a-8439-432b-80d1-982390482422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>903d87cd-bd06-4e4a-a525-fcd4a34f4145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a9ccc3db9791-1' and (text() = 'Lulus Kuliah' or . = 'Lulus Kuliah')]</value>
      <webElementGuid>1148e617-b985-4538-88ae-fa2c592e05e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
