<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Panduan TC_w-100</name>
   <tag></tag>
   <elementGuidId>ce2dabd6-1ca7-471f-9ee1-9d98e0ec956a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-6']/nb-dialog-container/ngx-tutorial-video/div/div/div/div/div/div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>587f5234-8e99-4bd8-81a1-64abba42f1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Registration guidance</value>
      <webElementGuid>22c27caa-23d3-4e02-bcd5-d1a6dfb5284f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b3a60d6-6bcc-414e-9076-c81cfa40c104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>b233b16a-d4d6-4b67-ad3c-5cec8cd59aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>7d4d5e91-50e4-449c-8e06-c1b8eb3869eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://videos.dyntube.com/iframes/YAm0NFBgkSFdzyBNVybQ</value>
      <webElementGuid>a6b420b0-ada8-46e7-82ad-71391f1df698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-6&quot;)/nb-dialog-container[1]/ngx-tutorial-video[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;vw-100&quot;]/div[@class=&quot;d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;col-12 col-md-10 col-lg-6&quot;]/div[@class=&quot;row d-flex flex-column rounded bg-white&quot;]/div[@class=&quot;col-12 p-3&quot;]/div[@class=&quot;body&quot;]/iframe[@class=&quot;w-100&quot;]</value>
      <webElementGuid>183d84dd-dfcb-446d-a530-576ddf2ffb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/nb-dialog-container/ngx-tutorial-video/div/div/div/div/div/div[2]/iframe</value>
      <webElementGuid>5b4105d4-663c-45db-9264-f495d09dda4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>954a8508-36bb-40fe-a6e9-c34e8db0acb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Registration guidance' and @src = 'https://videos.dyntube.com/iframes/YAm0NFBgkSFdzyBNVybQ']</value>
      <webElementGuid>71fd3358-24f3-4bc0-8b5f-431f2d4302ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
