<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Subscribe_dyt-icon-placeholder</name>
   <tag></tag>
   <elementGuidId>bd36eca3-963d-424b-a7b8-689065f9c679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dyt-icon-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dyntube-player[@id='vjs_video_3']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5093e238-80b9-4b4c-a4de-37fc972a5883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyt-icon-placeholder</value>
      <webElementGuid>0664f378-1b5b-4fb2-9c98-1e475901b961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3526a9ee-53ac-43a3-9568-fb19c0f992be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vjs_video_3&quot;)/button[@class=&quot;dyt-big-play-button&quot;]/span[@class=&quot;dyt-icon-placeholder&quot;]</value>
      <webElementGuid>1659e7b4-b172-458e-bf3f-0136dd44a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enigma Camp - Dashboard/iframe_Panduan TC_w-100</value>
      <webElementGuid>b8998287-27e9-4e11-9a68-bb32394d02a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dyntube-player[@id='vjs_video_3']/button/span</value>
      <webElementGuid>5c42aa54-08c1-4589-b4db-80f19351c631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>09b4b892-5ec2-40dc-8533-8c5b5d1ca221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
