<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SeeSchedule</name>
   <tag></tag>
   <elementGuidId>890d833f-c181-4cdb-a1bc-198e5675ba3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDownloadContract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDownloadContract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fdc9ef0-c57e-4816-b5ea-596da0ce6867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>a8bb0f60-8fd3-411b-8471-f09386bf7fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>455aa7d6-4b44-4e70-a9cf-9aa0fee7bd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>3f929020-e465-4e54-a204-3fc9b6efe236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e4f3a88-31fe-48cc-9f39-0e010d0e0a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadContract</value>
      <webElementGuid>a4514417-b87c-4953-a3ca-3e6bed75e586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-s-2 text-capitalize appearance-filled size-small shape-rectangle status-primary nb-transition</value>
      <webElementGuid>17fd600b-9174-4eb0-b668-ca8f36ad3ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f27b99a1-a1af-453e-a88f-12bb24ea7f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>275134ed-9c54-4221-92b0-9d951c73e580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Lihat Jadwal </value>
      <webElementGuid>edd90b9f-b378-457e-bbfe-c38f3e728a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDownloadContract&quot;)</value>
      <webElementGuid>debdc0cc-f6f5-49b8-bdea-1d21d797e19d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDownloadContract']</value>
      <webElementGuid>7be535a7-6d06-4807-beab-e9c9c97bacf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal T&amp;C Meeting'])[1]/following::button[1]</value>
      <webElementGuid>9764f918-ff60-4439-a374-ec84b3f6f4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Kelas'])[1]/following::button[1]</value>
      <webElementGuid>09f3c5ec-e257-4708-9acb-0f4f9081a785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/preceding::button[1]</value>
      <webElementGuid>8e1e6c8d-777c-42ca-96f7-893d7d8f7b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>ac1941b6-f39d-4c29-bcc3-dfbd32578d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDownloadContract' and (text() = '   Lihat Jadwal ' or . = '   Lihat Jadwal ')]</value>
      <webElementGuid>6a7c7cc4-0fd9-4eca-a01b-db6b0b3787e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
