<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialog_TncSchedule</name>
   <tag></tag>
   <elementGuidId>93f4eac4-caf5-4de1-a687-3a0ca35be92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mr-auto.fs-3.color-white.bold-600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-4']/nb-dialog-container/ngx-schedule-tnc/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cbcf8ad-3626-41af-8ccd-62948ccdf5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-auto fs-3 color-white bold-600</value>
      <webElementGuid>00b781a2-95b8-4b4e-8dee-341f48810bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silakan pilih jadwal T&amp;C Meeting yang tersedia</value>
      <webElementGuid>af523ddd-70db-4cd3-8abf-b60009c265b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-4&quot;)/nb-dialog-container[1]/ngx-schedule-tnc[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;d-flex flex-column bg-light rounded-lg mx-3 max-height-width&quot;]/div[@class=&quot;d-flex flex-row p-3 bg-primary rounded-top px-3&quot;]/div[@class=&quot;mr-auto fs-3 color-white bold-600&quot;]</value>
      <webElementGuid>1762ddbd-6489-43d1-8bc1-6ba380fe76d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-dialog-container/ngx-schedule-tnc/div/div/div/div</value>
      <webElementGuid>33ea9eea-9c76-40ef-b399-09ae3d4ee78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/following::div[11]</value>
      <webElementGuid>dae0ca08-dd22-454b-9f73-74a26071c7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari / Tanggal'])[1]/preceding::div[1]</value>
      <webElementGuid>e5b3659c-aa26-49fb-8255-34a4f274a468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minggu, 30 November 2025'])[1]/preceding::div[1]</value>
      <webElementGuid>e4a119ab-ed84-4634-b6c2-c06c8feab328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Silakan pilih jadwal T&amp;C Meeting yang tersedia']/parent::*</value>
      <webElementGuid>6899b8b1-13f0-4fb1-a94c-54765404f624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-schedule-tnc/div/div/div/div</value>
      <webElementGuid>82068d81-cc51-4f40-ba13-9e287f5361a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Silakan pilih jadwal T&amp;C Meeting yang tersedia' or . = 'Silakan pilih jadwal T&amp;C Meeting yang tersedia')]</value>
      <webElementGuid>3e88342d-c49a-460a-bb03-827c24a25981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
