<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_education_graduate</name>
   <tag></tag>
   <elementGuidId>30bf4cc3-420d-4e2a-a2ef-e9fe149ea6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Lulus Kuliah' or . = 'Lulus Kuliah')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a93658bc1681-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a93658bc1681-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3786d543-8f8f-40f4-b0d5-e90db69ddafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>d1a3e7fa-071e-4b17-8f46-3e98e9d7bc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d9e050ef-d974-4c5f-a2f3-104993e93c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3016b618-a5b0-4199-955b-12819f4362c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a93658bc1681-1</value>
      <webElementGuid>3a26b999-c36e-46d1-94a1-85d7b86b7a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lulus Kuliah</value>
      <webElementGuid>aed4d603-eb60-44a5-a740-0abb81e83c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a93658bc1681-1&quot;)</value>
      <webElementGuid>b29cde7d-053d-48b7-9b17-247da17f1c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a93658bc1681-1']</value>
      <webElementGuid>f5b371c0-c444-4e68-8322-4a2e43f87714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a93658bc1681']/div/div[2]/div[2]</value>
      <webElementGuid>c87afa5e-c231-4824-b1d3-d80d43a21fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa Aktif'])[2]/following::div[1]</value>
      <webElementGuid>c2a46d15-e746-46d2-8fb1-f0f7d53a0932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa Aktif'])[1]/following::div[6]</value>
      <webElementGuid>ef6bea58-869e-41f1-b5c1-0b30db05dd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus SMA/SMK Sederajat'])[1]/preceding::div[1]</value>
      <webElementGuid>022fb6a9-d1d1-4c48-95e6-2a5b85dd2c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>a1994ae5-4fd1-4048-88ad-389b8521b474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a93658bc1681-1' and (text() = 'Lulus Kuliah' or . = 'Lulus Kuliah')]</value>
      <webElementGuid>4c857838-c3c2-461b-b211-da66936ef591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
