<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat link</name>
   <tag></tag>
   <elementGuidId>d9bc7377-7bad-4fb1-b67e-c8feb38e0b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>889e2c08-e735-4326-a56c-cd42499f212f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>321ae3fa-821d-45f3-a890-d4d975850465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>e958956a-86dd-4d10-8f62-d3218cdb4558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>92999531-a356-4270-9e15-50847bc5be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f19a888-da4e-463f-856a-b402818a6672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign</value>
      <webElementGuid>8ce34e99-0d8d-471b-b5be-8589a4e1652f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-sm-2 mb-lg-0 text-capitalize btn-mb appearance-filled size-medium shape-rectangle status-info nb-transition</value>
      <webElementGuid>eedf5055-54d7-447e-ae8e-0a267ccf34d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c207acd-16e0-4c11-b4ec-e51b699353e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>57dad18a-ac43-418e-9ebf-5064e7f3e59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Buat link </value>
      <webElementGuid>293f69f8-cf26-4d86-b243-fdd5d11adbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;nb-theme-default                          pace-done&quot;]/ngx-app[1]/ngx-pages[@class=&quot;ng-star-inserted&quot;]/ngx-one-column-layout[1]/nb-layout[@class=&quot;window-mode with-scroll with-subheader&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-candidate-contract[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row p-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row pt-2&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/nb-accordion[3]/nb-accordion-item[@class=&quot;expanded&quot;]/nb-accordion-item-body[@class=&quot;ng-tns-c86-9 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c86-9 ng-trigger ng-trigger-accordionItemBody&quot;]/div[@class=&quot;item-body ng-tns-c86-9&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row pt-1 d-flex align-items-center&quot;]/div[@class=&quot;col-md-3 col-sm-2&quot;]/button[@id=&quot;sign&quot;]</value>
      <webElementGuid>6aa4c13d-f684-4f87-90e9-cce05f77807c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sign']</value>
      <webElementGuid>069eeca5-dd78-43fd-88a7-8e12d490a7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat link'])[1]/following::button[1]</value>
      <webElementGuid>05e8f099-663c-4a38-9cbd-ca3b820a667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda tangan kontrak'])[1]/following::button[1]</value>
      <webElementGuid>a99dbdaa-1f12-43e4-b4a1-1972fe87674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi akun'])[1]/preceding::button[1]</value>
      <webElementGuid>d4df71a9-f03f-4423-a1fe-54f415b0e273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item-body/div/div/div/div/div/button</value>
      <webElementGuid>3c2b2d3e-781e-49eb-8fee-94d68af7d6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'sign' and (text() = '  Buat link ' or . = '  Buat link ')]</value>
      <webElementGuid>12186cf2-805f-41ed-884a-4538f58a5873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
