<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat link</name>
   <tag></tag>
   <elementGuidId>d9bc7377-7bad-4fb1-b67e-c8feb38e0b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71ee2d74-b833-4344-bb90-03eb3968b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>e675fb93-9cb8-4e98-b2e1-57fe5c5b7b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>68cf272a-11f6-4374-ba5e-b5557eceb6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>d7e14bf8-6475-498b-9261-add5dd5286a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ab6903b-1c7a-4845-8e07-43fd1d5b3fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign</value>
      <webElementGuid>c11c109d-5f5e-4e42-8341-c624ea0801bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-sm-2 mb-lg-0 text-capitalize btn-mb appearance-filled size-medium shape-rectangle status-info nb-transition</value>
      <webElementGuid>b9affdff-4871-4ad3-85a8-dcb00ccadd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e2ba6da-b3cd-4105-aa1b-ca74aea2d993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96bee1b6-fb65-4875-a049-03d5a5adccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Buat link </value>
      <webElementGuid>24bc2a3e-282d-4efc-8b54-c2c68964f313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;nb-theme-default                            pace-done&quot;]/ngx-app[1]/ngx-pages[@class=&quot;ng-star-inserted&quot;]/ngx-one-column-layout[1]/nb-layout[@class=&quot;window-mode with-scroll with-subheader&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-candidate-contract[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row p-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row pt-2&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/nb-accordion[3]/nb-accordion-item[@class=&quot;expanded&quot;]/nb-accordion-item-body[@class=&quot;ng-tns-c86-9 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c86-9 ng-trigger ng-trigger-accordionItemBody&quot;]/div[@class=&quot;item-body ng-tns-c86-9&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row pt-1 d-flex align-items-center&quot;]/div[@class=&quot;col-md-3 col-sm-2&quot;]/button[@id=&quot;sign&quot;]</value>
      <webElementGuid>ddde338a-3853-4459-a3e4-6025b9334667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sign']</value>
      <webElementGuid>99aa0a33-62ec-439a-bdec-e8c2e18cf664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat link'])[1]/following::button[1]</value>
      <webElementGuid>f204530f-b2fe-4165-ad8b-2ed125b53905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda tangan kontrak'])[1]/following::button[1]</value>
      <webElementGuid>e754d722-ee19-4363-be11-6193f3b4cb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi akun'])[1]/preceding::button[1]</value>
      <webElementGuid>2c48c850-78af-4b5d-90aa-fe47814f6136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item-body/div/div/div/div/div/button</value>
      <webElementGuid>c11d611c-eed7-479a-bb0a-00cabd52256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'sign' and (text() = '  Buat link ' or . = '  Buat link ')]</value>
      <webElementGuid>8960d7b3-7bf1-4d27-9183-10d403d6dd2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
