<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>1de333a4-7217-4f02-bf9b-66b25364049d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-action-header.btn-box-none.p-3.text-dark.border-bottom-grey.d-flex.justify-content-between.appearance-ghost.full-width.size-medium.shape-rectangle.status-basic.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-9']/nb-popover/nb-overlay-container/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>054593ee-314a-4340-90e8-efbfbbb37a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action-header btn-box-none p-3 text-dark border-bottom-grey d-flex justify-content-between appearance-ghost full-width size-medium shape-rectangle status-basic nb-transition</value>
      <webElementGuid>13d41155-9594-4505-b479-6d891e73f35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1dbf0ac-77e8-43ac-9b9a-bab0fd5b2534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0008105-6237-43eb-809e-fa9415ef165c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar </value>
      <webElementGuid>fdafc451-7876-4ee8-a775-a8152a0ff66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-9&quot;)/nb-popover[@class=&quot;nb-overlay-bottom-start&quot;]/nb-overlay-container[1]/div[@class=&quot;d-flex flex-column ng-star-inserted&quot;]/button[@class=&quot;btn-action-header btn-box-none p-3 text-dark border-bottom-grey d-flex justify-content-between appearance-ghost full-width size-medium shape-rectangle status-basic nb-transition&quot;]</value>
      <webElementGuid>326983d1-aa60-46ba-8b29-549bb9f8a5f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-9']/nb-popover/nb-overlay-container/div/button[2]</value>
      <webElementGuid>40ce297e-234c-4685-98b7-0028a92f6c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/following::button[1]</value>
      <webElementGuid>0058fceb-9178-4663-984e-b12acdf15f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/following::button[2]</value>
      <webElementGuid>9583810c-b676-4d37-a4dc-62a22ca1c020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>ba090375-7b2d-4b91-9cdd-db40d6516721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-overlay-container/div/button[2]</value>
      <webElementGuid>a70095b6-4f44-465a-8a50-19994a7a0365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Keluar ' or . = 'Keluar ')]</value>
      <webElementGuid>9546f73c-84d2-4b3a-b0e4-7edd77f7231a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
