<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>1de333a4-7217-4f02-bf9b-66b25364049d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-action-header.btn-box-none.p-3.text-dark.border-bottom-grey.d-flex.justify-content-between.appearance-ghost.full-width.size-medium.shape-rectangle.status-basic.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-12']/nb-popover/nb-overlay-container/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89f2f02c-0d80-48fa-a9f1-a454100cac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action-header btn-box-none p-3 text-dark border-bottom-grey d-flex justify-content-between appearance-ghost full-width size-medium shape-rectangle status-basic nb-transition</value>
      <webElementGuid>0ee925f0-ffd2-4d19-b1d4-fc2d66ab58cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac7f38ab-9734-47ca-9781-60f7a123b198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>878ef0d4-c8df-4f8d-bbf6-35edc750ffda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar </value>
      <webElementGuid>ad8f913a-0324-4a5e-b506-887ff3591e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-12&quot;)/nb-popover[@class=&quot;nb-overlay-bottom-start&quot;]/nb-overlay-container[1]/div[@class=&quot;d-flex flex-column ng-star-inserted&quot;]/button[@class=&quot;btn-action-header btn-box-none p-3 text-dark border-bottom-grey d-flex justify-content-between appearance-ghost full-width size-medium shape-rectangle status-basic nb-transition&quot;]</value>
      <webElementGuid>0607e386-a8d8-4fc3-bde4-3c84cc443455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/nb-popover/nb-overlay-container/div/button[2]</value>
      <webElementGuid>4e5ed1b8-df3d-4daa-bd0c-054e453a8e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/following::button[1]</value>
      <webElementGuid>e0dc8186-e298-4472-a16b-ec73c2e9018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/following::button[2]</value>
      <webElementGuid>9f06e201-cce6-45bb-82bc-607758405c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>0fa008b9-6051-44d3-9e72-184783d5a7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-overlay-container/div/button[2]</value>
      <webElementGuid>75362bb4-c9d1-4fa4-8873-43c6da219db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Keluar ' or . = 'Keluar ')]</value>
      <webElementGuid>8649f9b2-83c0-4031-a961-0497ebcabad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
