<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseDialogActivation</name>
   <tag></tag>
   <elementGuidId>cde2df0b-5f50-4e89-b53a-335c98f8b5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide-modal-success-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='hide-modal-success-register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cefa7ad2-4ab4-4dd3-8d3c-2686be8baa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.enigmacamp.com/api/auth/icon-close.svg</value>
      <webElementGuid>2268922f-0ec6-47d8-9b43-4795dc73e26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-close</value>
      <webElementGuid>81fb10f0-ea5d-46bb-ac77-611cc30a7bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide-modal-success-register</value>
      <webElementGuid>ea1dc30a-6f8e-4838-b5d1-6db706f27e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>0864f505-20f8-4a17-807f-eb0a9ac43b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide-modal-success-register&quot;)</value>
      <webElementGuid>8b08812d-9b29-4bcc-922c-920b0bbabc37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='hide-modal-success-register']</value>
      <webElementGuid>100bcad0-91b5-4ef6-aba3-57e9af41cf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='successRegister']/div/div/div/div/div/div/div/img</value>
      <webElementGuid>7fbfd2d8-1f22-42c3-b91f-0c33bbfe177f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-close']</value>
      <webElementGuid>8fc9f71d-2576-4416-aec5-4505b87a1a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/img</value>
      <webElementGuid>369f80ea-7c30-471a-b918-f00d7cd1c31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.enigmacamp.com/api/auth/icon-close.svg' and @alt = 'icon-close' and @id = 'hide-modal-success-register']</value>
      <webElementGuid>08ea4a81-d71a-4ae1-9e8f-eaaf03307628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
