<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Tnc</name>
   <tag></tag>
   <elementGuidId>840600b6-bd7a-45b9-8325-f57c76325b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tnc-iconFailed > #tnc-iconFailed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='tnc-iconFailed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e31844ed-f445-4b47-ae80-65c45342acd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-regular fa-square</value>
      <webElementGuid>36afa320-3d8d-4b7d-a358-49ce14c707e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tnc-iconFailed</value>
      <webElementGuid>59eff34e-127f-4a54-bad9-410f09a43c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-register&quot;)/div[@class=&quot;row floating-label&quot;]/div[@class=&quot;col-12 d-flex align-items-start&quot;]/div[@class=&quot;col-1 text-end&quot;]/a[@id=&quot;tnc-iconFailed&quot;]/i[@id=&quot;tnc-iconFailed&quot;]</value>
      <webElementGuid>2229faf5-ed1c-4d02-b09b-32f28006cb24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='tnc-iconFailed']</value>
      <webElementGuid>d1a81e0b-5837-45c8-97c9-55dca52e0e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='tnc-iconFailed']/i</value>
      <webElementGuid>4a85e5f3-d5e3-421d-a9a8-ef186ce94dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/a/i</value>
      <webElementGuid>bd078666-f980-47f0-aa09-258def3f0515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'tnc-iconFailed']</value>
      <webElementGuid>d0b252b5-ee8e-481c-b75d-68de3294d5b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
