<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PasswordConfirmation</name>
   <tag></tag>
   <elementGuidId>4a6a160e-1333-4867-8979-86279ad6fe3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26b3270b-f58c-471d-9c08-b5225256c195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c7332241-1075-40da-82a9-2cf09fb01dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>ce660402-7ba8-4dbd-b00f-556b03b53e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>bc5b93b2-3ab5-4b59-aae7-97be5d934b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input text-medium color-medium input form-control font-size-14 invalid-input</value>
      <webElementGuid>70192e4d-0290-4179-95e8-df3dac3f12b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>00558fd7-41bd-4b6f-8270-46379c066cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>58bd7aed-5966-422b-a76c-516b5bcf8491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>aaac44c7-6bf3-48d2-b102-90497aa062a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpassword&quot;)</value>
      <webElementGuid>d06bbf41-1aae-4c63-a3bd-dd964e374692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpassword']</value>
      <webElementGuid>786746cc-1de6-41a5-bce3-f6b1447be60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-register']/div[6]/div/div[2]/input</value>
      <webElementGuid>2e142f92-23f3-4913-a2a1-153124d57a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>7a567de0-3e44-46c1-8dbe-a004e079da58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cpassword' and @name = 'cpassword' and @type = 'password']</value>
      <webElementGuid>51dcd648-8e78-465c-886f-8b10757cceb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
