<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kata Sandi_hide_eye</name>
   <tag></tag>
   <elementGuidId>d4da62fe-1acb-4f59-a3c4-7a465964e964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide_eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='hide_eye']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fe7493e3-23ad-4464-ace9-5b68f66d20b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash</value>
      <webElementGuid>c67dd004-e35a-44e4-8e5d-557e5465f160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide_eye</value>
      <webElementGuid>74679bd3-8b9b-4899-a827-0d3e8bf9194a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide_eye&quot;)</value>
      <webElementGuid>9a3dc309-5b78-44bb-a85b-65c6c5da535d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='hide_eye']</value>
      <webElementGuid>2e2b1a2f-c518-4137-a8cf-0814827add9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-register']/div[5]/div/div[3]/button/i[2]</value>
      <webElementGuid>9dcb0ee4-321b-4876-b22e-e2581b3c4326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>94cc7a0d-ddc3-4148-8d69-73e07299dac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'hide_eye']</value>
      <webElementGuid>a161caf9-aaee-449d-9fcd-29424a8524c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
