<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Setujui syarat dan ketentuan untuk be_d95a67</name>
   <tag></tag>
   <elementGuidId>0eccda06-98d0-426d-9d5d-e62535aeb742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captcha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb8a1b7e-3ff8-4db5-9024-6f7932b5e9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3e728d55-6cb1-46d2-9bc9-a0d05fc98be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>46918c0e-85f5-4434-b2a4-36b681d8f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>41a921c5-6935-4e41-a0a9-9b3e5b8187aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input text-medium color-medium form-control font-size-14 invalid-input</value>
      <webElementGuid>d95ddef4-e5ce-4b5e-9655-eedf100e4f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82f1c04a-c2a2-4395-ba92-3e1e2b9c94e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>da267b28-d79d-4f24-8c21-040bf7ebafc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>a7806abd-2f88-4775-afa7-36b819ece572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha&quot;)</value>
      <webElementGuid>f5986752-2887-4018-af2f-87018ddc8dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captcha']</value>
      <webElementGuid>fb5a208a-f475-428f-a8ea-c748646b7724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-register']/div[11]/div/div[2]/input</value>
      <webElementGuid>91411b54-401d-40da-81b6-51741319001c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/input</value>
      <webElementGuid>4083b5b1-6a7f-40f4-af44-99118c1606f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captcha' and @name = 'captcha' and @type = 'text']</value>
      <webElementGuid>f05baf5b-fc10-4f1b-913f-05d3d3960284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
