<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Subscribe_vjs_video_3_html5_api</name>
   <tag></tag>
   <elementGuidId>614b123f-c7d3-4349-93fb-fcf22e275cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vjs_video_3_html5_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='vjs_video_3_html5_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>08eb135c-f94b-4c6e-b6af-0029df0169be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bd2b3af8-f796-45fe-a92c-21097b9122c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>1e2578b5-5e1e-4009-8a6e-f03c4079b21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vjs_video_3_html5_api</value>
      <webElementGuid>144ef576-2073-43ad-b661-1f59b97be754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyt-tech</value>
      <webElementGuid>8cdb9bd2-72a9-4ab6-95e8-8ec6d7b89e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>53ac6e08-19ed-41cc-a5c5-3e6ea6364922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>playsinline</name>
      <type>Main</type>
      <value>playsinline</value>
      <webElementGuid>5a9f0dc8-a127-4665-b16c-86eeeb01901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1aa9c6de-f19a-4ce6-876e-9e849561daa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>https://cdn.dyntube.net/play/apn-s/data/aCdxuSEGHEWDk9wWvVl7Fg/videos/wn6mQTydFkiCu9casrsaRQ/v1/images/pubsrv/THA53EA7E4F10F01-LG.jpg</value>
      <webElementGuid>7e23a60e-62f7-481c-b370-01e894d05fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://videos.dyntube.com/839a3e00-7ee7-458f-bfe1-ff7197da35c1</value>
      <webElementGuid>68220c90-e01f-4d52-836e-33f1b19bf46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vjs_video_3_html5_api&quot;)</value>
      <webElementGuid>8b666131-dada-419f-9e69-270fd90496b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboard/iframe_Panduan TC_w-100</value>
      <webElementGuid>e78d7e64-4508-4b41-8073-5d627ac5df0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='vjs_video_3_html5_api']</value>
      <webElementGuid>8de2261f-debc-4fc7-831d-f350e1d412d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dyntube-player[@id='vjs_video_3']/video</value>
      <webElementGuid>372d747c-2ffd-406f-a31a-3aa5dcd3d3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>f3c5180f-f290-4977-b111-a6f3468f8a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'vjs_video_3_html5_api' and @src = 'blob:https://videos.dyntube.com/839a3e00-7ee7-458f-bfe1-ff7197da35c1']</value>
      <webElementGuid>79378e03-8485-453e-9596-5e7f3617d4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
