<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lewati</name>
   <tag></tag>
   <elementGuidId>a8385aa0-fb5c-4f2f-bd6b-94862879ab81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnDownloadContract'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cb8786a-0b1b-4d68-ab29-2410fb2e4423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>39c2aa1e-778c-4c2d-bad2-06ac23ca46d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>6dba4df9-c0f9-47d7-802f-155ca08e2831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>tiny</value>
      <webElementGuid>d785f86c-9a63-40a8-bdd4-9418940d84a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54762224-8196-491e-b036-7b42245f43f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadContract</value>
      <webElementGuid>4bed0b6c-fd16-415b-ba8a-05a8c466955d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mb-lg-0 text-capitalize appearance-outline size-tiny shape-rectangle status-primary nb-transition</value>
      <webElementGuid>3ef151c1-91e3-4b41-8cde-cd671a9d219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a369414e-f9c6-49d3-a91d-fcec810f41b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c436578-4be2-434c-91b0-3b6c64abbba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lewati   </value>
      <webElementGuid>7e06bcbc-314a-4f49-9c27-12eaab83bd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;nb-theme-default        pace-done&quot;]/ngx-app[1]/ngx-pages[@class=&quot;ng-star-inserted&quot;]/ngx-one-column-layout[1]/nb-layout[@class=&quot;window-mode with-scroll with-subheader&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-learning-method[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column mb-3 ng-star-inserted&quot;]/div[@class=&quot;px-0 col-12 bg-light border rounded d-flex flex-column&quot;]/div[@class=&quot;pt-2 pb-3 col-12 d-flex flex-column ng-star-inserted&quot;]/div[@class=&quot;p-2 d-flex flex-column flex-lg-row justify-content-between&quot;]/div[@class=&quot;d-flex flex-column mt-0 mt-lg-3&quot;]/div[@class=&quot;d-flex flex-wrap&quot;]/button[@id=&quot;btnDownloadContract&quot;]</value>
      <webElementGuid>1f26d4d3-3965-4270-91cb-22dd9c05d560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnDownloadContract'])[3]</value>
      <webElementGuid>c41aaa6a-0b29-49fa-81f8-be9241f71efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/preceding::button[1]</value>
      <webElementGuid>64263193-cff3-4656-bddd-5776fb7dd5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>d2046037-a23f-4115-aeca-6452473c36d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDownloadContract' and (text() = ' Lewati   ' or . = ' Lewati   ')]</value>
      <webElementGuid>60c1f92f-fa2f-4777-b009-067ae376a46d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
