<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Attend</name>
   <tag></tag>
   <elementGuidId>c1912e14-63f6-426a-8fc4-344e79ee492f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDownloadContract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDownloadContract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6934fc9c-2e40-4100-9eb0-8a713deb326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>57ceda95-6468-4aed-9254-50861372309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>e4d45808-b91d-40de-8b98-ff71832f3bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>tiny</value>
      <webElementGuid>798d9956-9f61-43c3-ae7c-1c7d61e905c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ab91e37-7ea4-4822-88e8-31d741104ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadContract</value>
      <webElementGuid>d73aef37-f687-4a89-a370-48dd1ce8c674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mb-lg-0 text-capitalize mr-2 appearance-filled btn-disabled size-tiny shape-rectangle status-primary nb-transition</value>
      <webElementGuid>2b50f9b2-5ddd-47d1-8708-8aa5c78365ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>574f0b04-37f4-4cf9-be85-9966fed9e592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8e5ecea5-824b-4b68-b4b5-1512e9381dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hadir   </value>
      <webElementGuid>be7bd1f6-2a22-4e73-b403-b0a7dac71864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;nb-theme-default        pace-done&quot;]/ngx-app[1]/ngx-pages[@class=&quot;ng-star-inserted&quot;]/ngx-one-column-layout[1]/nb-layout[@class=&quot;window-mode with-scroll with-subheader&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-learning-method[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column mb-3 ng-star-inserted&quot;]/div[@class=&quot;px-0 col-12 bg-light border rounded d-flex flex-column&quot;]/div[@class=&quot;pt-2 pb-3 col-12 d-flex flex-column ng-star-inserted&quot;]/div[@class=&quot;p-2 d-flex flex-column flex-lg-row justify-content-between&quot;]/div[@class=&quot;d-flex flex-column mt-0 mt-lg-3&quot;]/div[@class=&quot;d-flex flex-wrap&quot;]/button[@id=&quot;btnDownloadContract&quot;]</value>
      <webElementGuid>d6295345-37f0-4e5f-8eda-25153b55cae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDownloadContract']</value>
      <webElementGuid>e47eea8a-00d1-4e11-87c9-f77d57428393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kehadiran'])[1]/following::button[1]</value>
      <webElementGuid>785efd7e-127e-4bfa-b80d-99dabd869b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://meet.google.com/oxd-tioh-nyv'])[1]/following::button[1]</value>
      <webElementGuid>05814044-8851-46b6-880b-efd03dcc0bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>8585d0f3-c5d2-4b06-946a-de4555b4e298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDownloadContract' and (text() = ' Hadir   ' or . = ' Hadir   ')]</value>
      <webElementGuid>c88358c0-ea91-4545-8e52-7c9e1b5d34e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
