<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialog_TncGuide</name>
   <tag></tag>
   <elementGuidId>dd97ab24-08fc-46b1-abc5-1d90f5c82877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header.d-flex.justify-content-between</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-6']/nb-dialog-container/ngx-tutorial-video/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ac6bee6-7306-4811-a487-a0570db1d5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header d-flex justify-content-between</value>
      <webElementGuid>a306492f-9606-4e6b-953d-76626f49472c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panduan T&amp;C</value>
      <webElementGuid>9d1c6b40-22de-47be-acd4-0fd59c8ed4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-6&quot;)/nb-dialog-container[1]/ngx-tutorial-video[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;vw-100&quot;]/div[@class=&quot;d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;col-12 col-md-10 col-lg-6&quot;]/div[@class=&quot;row d-flex flex-column rounded bg-white&quot;]/div[@class=&quot;col-12 p-3&quot;]/div[@class=&quot;header d-flex justify-content-between&quot;]</value>
      <webElementGuid>ee8cce29-ecb6-411b-b7fe-a611367a3550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/nb-dialog-container/ngx-tutorial-video/div/div/div/div/div/div</value>
      <webElementGuid>d3eb9711-fdeb-4a3c-9b88-7737ed3396d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enigmacamp.com'])[1]/following::div[13]</value>
      <webElementGuid>3f80e42a-ce13-4697-97ec-512c364956e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya mengerti'])[1]/preceding::div[3]</value>
      <webElementGuid>3ed64685-d678-4c25-847f-8ba9c612be53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-tutorial-video/div/div/div/div/div/div</value>
      <webElementGuid>fbe703c6-0b88-42ae-bd9d-cc9f5cc820e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Panduan T&amp;C' or . = 'Panduan T&amp;C')]</value>
      <webElementGuid>111d9d23-c1d2-4129-848f-413faa785a18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
