<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lulus Kuliah</name>
   <tag></tag>
   <elementGuidId>b3ec90ae-a918-4729-95fd-2b911ebd147c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a0d6b646de1a-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a0d6b646de1a-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e4625cc-1fb7-4d02-aa05-f326e3f7af90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>ddd674b8-d865-40ae-9d7d-eeb2fa687e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5eea9964-1d83-4fa3-8cd4-28a2afa90ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72980486-17cf-4593-954b-68355564919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a0d6b646de1a-1</value>
      <webElementGuid>47ca8afe-fbb1-4f99-b475-f3740d6efa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lulus Kuliah</value>
      <webElementGuid>81eaf11e-10f8-4d0a-91fe-c9083f8ebefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a0d6b646de1a-1&quot;)</value>
      <webElementGuid>1809746d-f9ce-47a0-83fc-9cc451f9b6ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a0d6b646de1a-1']</value>
      <webElementGuid>851133da-ef7e-4569-a0fa-ef36b0680f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a0d6b646de1a']/div/div[2]/div[2]</value>
      <webElementGuid>bc46819b-b8c9-4539-9ae7-448906a0730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa Aktif'])[1]/following::div[1]</value>
      <webElementGuid>afb90e79-b6af-4d65-bc12-a1c78d0cecdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Pendidikan Terakhir'])[1]/following::div[6]</value>
      <webElementGuid>cfdb7033-a4f5-461f-bb6c-eb29e168a40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus SMA/SMK Sederajat'])[1]/preceding::div[1]</value>
      <webElementGuid>c91c1133-5312-476e-a466-bf6ac5dd6ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>bb7a84d4-31c3-4eb8-9029-8e26de8f7504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a0d6b646de1a-1' and (text() = 'Lulus Kuliah' or . = 'Lulus Kuliah')]</value>
      <webElementGuid>2d1c5033-6873-4aa5-aac5-4a5a0ce3570f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
