<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BOGOR</name>
   <tag></tag>
   <elementGuidId>8da686c7-592f-4918-90bb-4eef016c17db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a9995ac75c4d-86</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a9995ac75c4d-86']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1daf06ea-9627-495f-b7aa-01cacea05598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>22975e39-88ef-42f9-99f0-651a2fd0c31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>84f2bcd9-19fc-4f3a-a207-0484d42616f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dbea117b-a6da-4b4a-b057-465c1b9b7184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a9995ac75c4d-86</value>
      <webElementGuid>ad5c1951-ce70-4d15-bc66-72962a3845a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOGOR</value>
      <webElementGuid>4c467bd8-f17c-4827-b50d-4d203aa35871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a9995ac75c4d-86&quot;)</value>
      <webElementGuid>17e744ca-91a6-463b-ba91-47fe977dd727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a9995ac75c4d-86']</value>
      <webElementGuid>d73276b3-a430-43b0-b586-cf719e4b89b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a9995ac75c4d']/div/div[2]/div[3]</value>
      <webElementGuid>c522e5de-28be-4c0f-a835-0e018289eb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOALEMO'])[1]/following::div[1]</value>
      <webElementGuid>6aefc2ba-252d-46af-a71e-d51cec2477d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMBON'])[1]/following::div[2]</value>
      <webElementGuid>762d553c-7520-432b-a8f0-12dd3c7ec372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOGOR'])[2]/preceding::div[1]</value>
      <webElementGuid>eb6258c0-ee65-47e4-bf01-16ccd1bec530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[3]</value>
      <webElementGuid>49d3cf2b-b00a-414b-9be3-b295a73abf0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a9995ac75c4d-86' and (text() = 'BOGOR' or . = 'BOGOR')]</value>
      <webElementGuid>2b7f877f-91cd-4901-babb-fb25122e86b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
