<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Swafoto (selfie)_inputSelfie</name>
   <tag></tag>
   <elementGuidId>6cc6bc57-8531-458e-8cc6-1cf725a9a785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputSelfie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSelfie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5042386-0a48-4407-aeaa-1abd0065ab74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSelfie</value>
      <webElementGuid>0d13dcf6-7e12-40f5-8592-460462b91b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selfie</value>
      <webElementGuid>97c05ff5-fca8-459d-bbad-8cb23d3c3d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8961a3c8-ec92-4441-9d8b-d6eed850b8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Selfie camera</value>
      <webElementGuid>3eeb0cf5-148b-4b69-9e4c-e1bd464f1fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0418f467-596f-4c28-bde9-8ab3b8ad90d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSelfie&quot;)</value>
      <webElementGuid>8b03b807-01bf-4ff4-bb81-f31212512748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSelfie']</value>
      <webElementGuid>5277aec3-a358-4a16-8436-4e2c5bdb68b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c668e4d8-7a9c-44ed-8fb6-12aca260ba81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputSelfie' and @type = 'text']</value>
      <webElementGuid>3d60aaaa-2c55-454a-9ada-d90fd2f12f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
