<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hadir beda sesi</name>
   <tag></tag>
   <elementGuidId>0411b29d-522b-4043-beec-fa2f886ead38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnDownloadContract'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ce1b848-86b7-4c77-ab5a-829a7b2fc04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>bfeafca6-25b2-47c1-9f8c-0ac8e2dd17ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>924a6077-04dd-4977-b3af-6bbd77d4300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>tiny</value>
      <webElementGuid>69d72aa0-7f8f-43d4-94af-edd30888a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51e26bde-dfe5-41fe-b39b-9f6e53bd927e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadContract</value>
      <webElementGuid>40aa35c2-e7b8-4c75-9087-fb0144493faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mb-lg-0 text-capitalize mr-2 appearance-filled size-tiny shape-rectangle status-primary nb-transition</value>
      <webElementGuid>2d51915d-6657-4bc0-ab6c-e9dbcf2e4454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f00102c-a5cb-41bb-817d-6e9f495f2e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>407b1315-f053-4b24-a61d-77c8b9de263a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hadir beda sesi   </value>
      <webElementGuid>378f7a7c-4185-48bc-827c-222242b65b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;nb-theme-default      pace-done&quot;]/ngx-app[1]/ngx-pages[@class=&quot;ng-star-inserted&quot;]/ngx-one-column-layout[1]/nb-layout[@class=&quot;window-mode with-scroll with-subheader&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-learning-method[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column mb-3 ng-star-inserted&quot;]/div[@class=&quot;px-0 col-12 bg-light border rounded d-flex flex-column&quot;]/div[@class=&quot;pt-2 pb-3 col-12 d-flex flex-column ng-star-inserted&quot;]/div[@class=&quot;p-2 d-flex flex-column flex-lg-row justify-content-between&quot;]/div[@class=&quot;d-flex flex-column mt-0 mt-lg-3&quot;]/div[@class=&quot;d-flex flex-wrap&quot;]/button[@id=&quot;btnDownloadContract&quot;]</value>
      <webElementGuid>1c8ce705-12f0-4adf-aff0-2aff56749a28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnDownloadContract'])[2]</value>
      <webElementGuid>5dce4825-372d-478b-89a4-98dec076ca6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kehadiran'])[1]/following::button[2]</value>
      <webElementGuid>72c8ba34-f3ae-4ab1-85d3-c3b01f58229e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9b614663-5f23-4e70-8391-7471d4893ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDownloadContract' and (text() = ' Hadir beda sesi   ' or . = ' Hadir beda sesi   ')]</value>
      <webElementGuid>d29320cc-041d-4b5a-93d2-cda22893a802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
