<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih jadwal</name>
   <tag></tag>
   <elementGuidId>393c1b54-ae81-4f3d-9192-7467570de8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPickSchedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPickSchedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac652c14-1d66-4052-80c9-2c2ab05014b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>ed9906c6-c7ad-4312-8438-26d60504e1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>6ebded9a-2cbf-4be2-aa23-aa49252df97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>tiny</value>
      <webElementGuid>f48a4601-95e8-422e-a844-ce530a446b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e7599dc-d215-4275-9d35-de27e40aedfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPickSchedule</value>
      <webElementGuid>a966c66e-db2d-4376-9aa6-6600e1faf8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-s-2 text-capitalize appearance-filled size-tiny shape-rectangle status-primary nb-transition</value>
      <webElementGuid>c78bc4d3-bb04-4095-b1a1-8bcdecf47a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>869159d9-4797-43d3-a49e-166d49277428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60d96d1e-109f-489f-b6a0-75abad2cf643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Pilih jadwal </value>
      <webElementGuid>cfa04b2b-9cd8-4b21-8dfd-5839a47a9eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPickSchedule&quot;)</value>
      <webElementGuid>d64bf2cb-ea95-4d94-809c-ee0d73d4a78a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPickSchedule']</value>
      <webElementGuid>94efc959-03d0-409f-bcef-394d9b6bff03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/nb-dialog-container/ngx-schedule-tnc/div/div/div[2]/div/div/div/div/div[5]/button</value>
      <webElementGuid>71737956-369f-433e-b762-dbbd20b84b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://meet.google.com/oxd-tioh-nyv'])[1]/following::button[1]</value>
      <webElementGuid>a789e1f3-bcf6-44db-82d3-0de7a1ac460b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link meeting'])[1]/following::button[1]</value>
      <webElementGuid>d85fb378-6b0d-4a9e-a581-41e2304faa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>1b62a539-91bf-493f-b41e-397f2d1518bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPickSchedule' and (text() = '   Pilih jadwal ' or . = '   Pilih jadwal ')]</value>
      <webElementGuid>e53704f7-3fc9-4bbd-9919-1218475cd5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
