<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih jadwal</name>
   <tag></tag>
   <elementGuidId>393c1b54-ae81-4f3d-9192-7467570de8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPickSchedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPickSchedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd222ed8-aa71-40f2-9baf-3121d99d5685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rectangle</value>
      <webElementGuid>e791d911-244c-4618-b820-74dc240e820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>791d7291-a58b-4026-864e-461e41ea87ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>tiny</value>
      <webElementGuid>9f1b2525-93c5-4bbe-a567-7b85bfd84f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1feb4b98-44e0-446c-807b-85d51a67b865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPickSchedule</value>
      <webElementGuid>8afb64e6-8e3d-495d-a306-b0d579373656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-s-2 text-capitalize appearance-filled size-tiny shape-rectangle status-primary nb-transition</value>
      <webElementGuid>f24464db-6d64-44d6-a7de-fb24f8f213d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>737245c0-7f18-453f-9a64-a8d787293779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a1c2dfe-93a9-46ab-bfdc-81968e9a3759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Pilih jadwal </value>
      <webElementGuid>794b9b40-ebab-4f5a-985a-b5ad2c2ddb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPickSchedule&quot;)</value>
      <webElementGuid>bb36b174-b870-479f-9f44-8442d8c63283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPickSchedule']</value>
      <webElementGuid>d83579c8-7be4-470e-a35b-26f4fcfc1119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/nb-dialog-container/ngx-schedule-tnc/div/div/div[2]/div/div/div/div/div[5]/button</value>
      <webElementGuid>85c3ddbe-7012-4f60-9907-562514ea1118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://meet.google.com/oxd-tioh-nyv'])[1]/following::button[1]</value>
      <webElementGuid>a3b45d70-f874-4563-81f7-ef9d1989889c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link meeting'])[1]/following::button[1]</value>
      <webElementGuid>76de73e0-c10b-4825-aa5b-e60fb3a17277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>47544ec6-faea-4969-9cac-55eb00ab3540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPickSchedule' and (text() = '   Pilih jadwal ' or . = '   Pilih jadwal ')]</value>
      <webElementGuid>31b2c468-dc1b-41f5-a975-62845dbf54cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
