<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lulus Kuliah</name>
   <tag></tag>
   <elementGuidId>6e038b3f-7eee-4e11-a040-43fd39ef2d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aaabd3a3131b-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aaabd3a3131b-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47a5726f-05de-4a9d-b4c2-8c71e463bcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>909ae351-04cc-4d36-8c7f-3d437cd4fb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c280cc42-ab80-467c-a37f-388abc5eac8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59c5ac20-6ed7-4635-9ba3-91e5f7ce3233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aaabd3a3131b-1</value>
      <webElementGuid>ab208588-b381-421e-b5ae-1d1766d32046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lulus Kuliah</value>
      <webElementGuid>ac9df1e4-de8d-4681-9d50-2dddb73f27e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aaabd3a3131b-1&quot;)</value>
      <webElementGuid>c59fe4fe-b44c-40b7-8edf-8bf8bc1c6445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aaabd3a3131b-1']</value>
      <webElementGuid>8847f5e9-cf7d-448a-9586-9612be39a486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aaabd3a3131b']/div/div[2]/div[2]</value>
      <webElementGuid>bffbf7af-3b23-4f99-bdc3-a732b026f2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa Aktif'])[1]/following::div[1]</value>
      <webElementGuid>dea99c4e-0320-449b-b5b1-b88fa4599f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Pendidikan Terakhir'])[1]/following::div[6]</value>
      <webElementGuid>9241f537-9a7e-4398-9b7e-6ded292fe7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus SMA/SMK Sederajat'])[1]/preceding::div[1]</value>
      <webElementGuid>25847d3c-d153-463a-a6ee-10b6cb84dc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>d2d8805c-6629-48eb-baf3-af2e109badba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aaabd3a3131b-1' and (text() = 'Lulus Kuliah' or . = 'Lulus Kuliah')]</value>
      <webElementGuid>71fd8db3-5eb2-47ba-a70e-64b1b682623d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
